### ISSUE TITLE
Error during testing image recognition (repeating untill specifying service&topic)

### ISSUE THREAD

**Issue by JosjaG** [tue-robotics/image_recognition#24]
[ERROR] [1509800338.863343]: [32FC1] is not a color format. but [bgr8] is. The conversion does not make sense
[ERROR] [1509800338.863639]: bad callback: <bound method TestPlugin._image_callback of <image_recognition_rqt.test.TestPlugin object at 0x7ff759ead218>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/amigo/ros/kinetic/system/src/image_recognition_rqt/src/image_recognition_rqt/test.py", line 134, in _image_callback
    self._image_widget.set_image(cv_image)
UnboundLocalError: local variable 'cv_image' referenced before assignment

**Comment by reinzor** [comment]
Fixed by https://github.com/tue-robotics/image_recognition/commit/93d095e6ff45040f09cb94bf7828a305b96dceb0
