### ISSUE TITLE
Tensorflow crash when sending empty image

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/image_recognition#3]
Traceback (most recent call last):
      File "/home/amigo/ros/indigo/system/src/tensorflow_ros/scripts/object_recognition_node.py", line 184, in <module>
        object_recognition.update()
      File "/home/amigo/ros/indigo/system/src/tensorflow_ros/scripts/object_recognition_node.py", line 122, in update
        predictions = sess.run(result_tensor, {'DecodeJpeg/contents:0': f.read()})
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
        run_metadata_ptr)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
        feed_dict_string, options, run_metadata)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
        target_list, options, run_metadata)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors.InvalidArgumentError: Invalid JPEG data, size 0
       [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)]]

    Caused by op u'DecodeJpeg', defined at:
      File "/home/amigo/ros/indigo/system/src/tensorflow_ros/scripts/object_recognition_node.py", line 179, in <module>
        save_images_folder=save_images_folder)
      File "/home/amigo/ros/indigo/system/src/tensorflow_ros/scripts/object_recognition_node.py", line 61, in __init__
        _ = tf.import_graph_def(graph_def, name='')
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
        op_def=op_def)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
        self._traceback = _extract_stack()

    InvalidArgumentError (see above for traceback): Invalid JPEG data, size 0
    	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)]]

**Comment by LoyVanBeek** [comment]
Aij!

**Comment by LoyVanBeek** [comment]
I am LoyBoy
